/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.unisabana.dyas;

public class App {
    public String getGreeting() {
        return "Qhubo parcero";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
